language: node_js

node_js:
  - 6.0.0

# establish environment variables
env:
  global:
    - GH_USER_NAME="vladimirpodr"
    - GH_USER_EMAIL="vladimirpodr@gmail.com"
    - GH_REPO="vladimirpodr/terraform-example"
    # encrypted GH_TOKEN and AWS credentials
    - secure: "TybH2rcYSc699fkGDb1Jb4W+yOIgyUxoLTWrjT551Vxe4tY4zCiU83J+yNt+WBv09PDZg1YpURrEczLCi2UAfq0FyUskui5FwTYN065ZxYtXaw/htMAzI9wKAlbk4uQk1NZLD2JOA/RHcdadRiUZ3xVJ4b+F8ee8e81tN6BmE9Y74GeKFYcibnSvrdBzahUV3p1J+TtqzeqB6UiG4LqHHX8xGcQVl8T5Vz/nWFgjdOdFruEeBsPi5lfrV00iOi6DsCRaa5ltPAZZgVUv4uF1bJyvje3PUq8DCQscXO/rUTFOes2x66cVYDtYgVBchmvSD3RSH/cx2mo6EJiFZ9hrHhCwcNGO5lVJb7WPbG9oV63KHMGF4438+Qd5aOKZaQ2HUCzJf7zduZs0FwNuO5m9HQroQV+eq1BB8sf6R5SqWCp19jdp4KEwM87h8OfDoxZ+P/QFE/7ka9Sb7BIWxTUzks92ba9TH/igY4MEr6L3vP6zNVsw1ybakyRZ3+CIxW0o2cYf8LZC0DJ1nvNgnBpovp2PwP7G7BS77F7WndCxYF3c4oIRzODjNTT8vhKS6TLMDQphjdTDytc1v3J8hd+sh5IZxS3aNge6ZvuIDXzAFDnNppcYZhbsnkT7aVxdr1V1sOk5rNLj3RwxGhbr4tFo60aDoLJ+NGq0ycIFu7+RN4I="

# install ruby sass/compass for use by gulp-node-sass
before_install:
  - gem install sass -v 3.4.22
  - gem install compass -v 1.0.3

install:
  - npm install

script:
  - npm run build

# install terraform
before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# terraform apply
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: vladimirpodr/terraform-example
      branch: master
